apiVersion: apps/v1
kind: Deployment
metadata:
  name: photostudio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photostudio
  template:
    metadata:
      labels:
        app: photostudio
    spec:
      containers:
      - name: photostudio
        image: venkataramana773/photostudio-project-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_AUTH_URI
          value: mongodb://mongo:27017/artgallery
