apiVersion: apps/v1
kind: Deployment
metadata:
  name: photostudio-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photostudio
  template:
    metadata:
      labels:
        app: photostudio
    spec:
      containers:
      - name: photostudio
        image: venkataramana773/photostudio-app:latest
        ports:
        - containerPort: 3000
